[build]
  command = "npm run build"
  publish = "dist"  # Pasta de saída do front-end
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
