apiVersion: apps/v1
kind: Deployment
metadata:
  name: church-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: church-management-api
  template:
    metadata:
      labels:
        app: church-management-api
    spec:
      containers:
        - name: church-management-api
          image: dan1993/api-church:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: church-api-config
            - secretRef:
                name: church-api-secrets
