apiVersion: v1
kind: Service
metadata:
  name: church-management-api
spec:
  type: LoadBalancer
  selector:
    app: church-management-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
