apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "church-api.fullname" . }}-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  target:
    name: church-api-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: church-api
        property: DATABASE_URL
