name: CD to AKS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (dev, staging ou prod)"
        required: true
        default: "dev"

env:
  TF_VAR_location: "eastus"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Select tfvars file
        id: tfvars
        run: |
          case "${{ github.event.inputs.environment }}" in
            dev) echo "file=terraform.dev.tfvars" >> "$GITHUB_OUTPUT" ;;
            staging) echo "file=terraform.stage.tfvars" >> "$GITHUB_OUTPUT" ;;
            *) echo "file=terraform.tfvars" >> "$GITHUB_OUTPUT" ;;
          esac

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -var-file=${{ steps.tfvars.outputs.file }}

      - name: Terraform Apply
        id: apply
        working-directory: ./infra
        run: terraform apply -auto-approve -var-file=${{ steps.tfvars.outputs.file }}

      - name: Get kubeconfig
        id: kubeconf
        working-directory: ./infra
        run: |
          terraform output -raw kube_config > kubeconfig
          echo "kube_config=$(cat kubeconfig)" >> "$GITHUB_OUTPUT"

      - name: Set Kubeconfig
        run: |
          echo "${{ steps.kubeconf.outputs.kube_config }}" > ${{ runner.temp }}/kubeconfig
          echo "KUBECONFIG=${{ runner.temp }}/kubeconfig" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy App with Helm
        run: |
          helm upgrade --install church-api ./helm/church-api \
            -f helm/church-api/values-${{ github.event.inputs.environment }}.yaml \
            --namespace ${{ github.event.inputs.environment }} --create-namespace

