name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - develop  # Roda nas mudanças na branch 'master'
  pull_request:
    branches:
      - stage  # Roda para Pull Requests na branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Build the project
      run: yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
         docker build -t dan1993/api-church:latest .
         docker tag dan1993/api-church:latest dan1993/api-church:${{ github.sha }}
         docker push dan1993/api-church:latest
         docker push dan1993/api-church:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.1.122.82 << 'EOF'
          sudo docker pull dan1993/api-church:latest
          sudo docker stop api-church || true
          sudo docker rm api-church || true
          sudo docker run -d -p 3000:3000 --name api-church dan1993/api-church:latest
        EOF
          # Opcional: aplicar no cluster Kubernetes
          if [ -n "${{ secrets.KUBE_CONFIG_DATA }}" ]; then
            echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
            kubectl --kubeconfig kubeconfig apply -f k8s/
          fi
