name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Roda nas mudanças na branch 'develop'
  pull_request:
    branches:
      - master  # Roda para Pull Requests na branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run Tests
    #   run: npm test

    - name: Build the project
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-92-205-240.compute-1.amazonaws.com << 'EOF'
          cd /church-management-api-node
          git pull origin master
          npm install
          npm run build
          pm2 restart church
        EOF
