name: Quality

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=church-api
            -Dsonar.organization=danylo93
            -Dsonar.sources=src
